env:
  PROJECT_DIR: core-components
  TARGET_BRANCH: ${{ secrets.LIBRARY_BRANCH_DEV }}
  TARGET_REPO: ${{ secrets.LIBRARY_REPOSITORY }}
  USER_EMAIL: ${{ secrets.LIBRARY_USER_EMAIL }}
  USER_NAME: ${{ secrets.LIBRARY_USER_NAME }}
  USER_PWD: ${{ secrets.LIBRARY_PASSWORD }}
jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        path: sub
    - continue-on-error: true
      name: Clean project
      run: 'git -C sub log --format="%an : %s" -n 1 > commit.txt

        rm -rf sub/.git

        rm -rf sub/.github

        '
    - continue-on-error: true
      name: Set git config
      run: 'git config --global credential.helper cache

        git config --global user.email ${USER_EMAIL}

        git config --global user.name ${USER_NAME}

        '
    - continue-on-error: true
      name: Checkout main project
      run: git clone -b ${TARGET_BRANCH} https://${USER_EMAIL}:${USER_PWD}@${TARGET_REPO}
        main
    - continue-on-error: true
      name: Move project to main
      run: "rm -rf main/${PROJECT_DIR} \nmv sub main/${PROJECT_DIR}\n"
    - continue-on-error: true
      name: Commit Changes
      run: 'pushd main

        git add ${PROJECT_DIR}

        git commit -F ../commit.txt

        git push

        popd

        '
name: Deploy to Components Library
on:
  repository_dispatch:
    types: trigger-ga___maven-deploy-to-library.yml
