jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build & Test with Maven
      run: mvn -B -U clean install ${{ matrix.profile }} -s ./.github/workflows/settings.xml
    - continue-on-error: true
      name: Run core coverage check
      run: bash <(curl -s https://codecov.io/bash)
    strategy:
      matrix:
        java:
        - 8
        - 11
        os:
        - ubuntu-latest
        profile:
        - ''
        - -Pcloud,adobe-public
  build-js:
    defaults:
      run:
        working-directory: content
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: content/package-lock.json
        node-version: ${{ matrix.node-version }}
    - continue-on-error: true
      name: Install dependencies
      run: npm install
    - continue-on-error: true
      name: Run lint
      run: npm run eslint
    - continue-on-error: true
      name: Run tests
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI --singleRun=true
    strategy:
      matrix:
        node-version:
        - 14
name: Test
on:
  repository_dispatch:
    types: trigger-ga___maven-test.yml
