jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
        GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      name: Import GPG key
      run: 'echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch
        --yes

        echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust --no-tty
        --batch --yes

        '
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        X_GITHUB_PASSWORD: ${{ secrets.ADOBE_BOT_GITHUB_PASSWORD }}
        X_GITHUB_USERNAME: ${{ secrets.ADOBE_BOT_GITHUB_USERNAME  }}
      name: Deploy to Central Repository
      run: mvn -B -Prelease,cloud,ossrh,adobe-public -s ./.github/workflows/settings.xml
        clean deploy -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
name: Deploy to OSSRH
on:
  repository_dispatch:
    types: trigger-ga___maven-deploy.yml
